name: Adventures in Cardboard
favicon: null
layout_spectrum: 0.63275
typography_spectrum: 0.32065
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c0d21'
    - '#df2f3c'
    - '#fdcc3f'
    - '#a88b63'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
