analytics: {}
color:
  brandColors:
    - '#050505'
    - '#faf9f4'
    - '#cec0b5'
    - '#826603'
    - '#f8e968'
  brandStrength: 0
  lightness: 0
  rhythmicContrast: 0.25
  saturation: 0.197072
cta: {}
layout_spectrum: 0.18094
name: Adventures in Cardboard
opengraph: {}
purpose: []
typography_spectrum: 0.25202
