analytics: {}
color:
  brandColors:
    - '#010100'
    - '#444444'
    - '#c84b0f'
    - '#e2e1b3'
    - '#f1a709'
  brandStrength: 0
  lightness: 0.725225
  rhythmicContrast: 0.25
  saturation: 0.256755
cta: {}
layout_spectrum: 0.673423
name: Adventures in Cardboard
opengraph: {}
purpose: []
typography_spectrum: 0.34955
