analytics: {}
color:
  brandColors:
    - '#B0B8C0'
    - '#988040'
    - '#687080'
    - '#A85850'
    - '#D0B878'
  brandStrength: 0.5
  lightness: 0.8125
  rhythmicContrast: 1
  saturation: 0.3125
cta: {}
layout_spectrum: 0.63275
name: Adventures in Cardboard
opengraph: {}
purpose: []
typography_spectrum: 0.32065
