name: Adventures in Cardboard
favicon: null
layout_spectrum: 0.62712
typography_spectrum: 0.34955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0b0d'
    - '#ffffff'
    - '#c3c9ca'
    - '#e25d31'
    - '#74818e'
  brandStrength: 0.5
  lightness: 0.7275523077696562
  saturation: 0.4943357640877366
  rhythmicContrast: 1
purpose: []
