name: Adventures in Cardboard
favicon: null
layout_spectrum: 0
typography_spectrum: 0.34955
title: Deathbunny Plays Games
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010100'
    - '#444444'
    - '#c84b0f'
    - '#e2e1b3'
    - '#f1a709'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
