name: Adventures in Cardboard
favicon: null
layout_spectrum: 0.18094
typography_spectrum: 0.25202
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#faf9f4'
    - '#cec0b5'
    - '#826603'
    - '#f8e968'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
