name: Adventures in Cardboard
favicon: null
layout_spectrum: 0
typography_spectrum: 0.34955
title: Deathbunny Plays Games
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0b0d'
    - '#ffffff'
    - '#c3c9ca'
    - '#e25d31'
    - '#74818e'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
