name: Adventures in Cardboard
favicon: null
layout_spectrum: 0.19605140038765967
typography_spectrum: 0.44829358835704625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6206246290821582
  lightness: 0.7275523077696562
  saturation: 0.4943357640877366
  rhythmicContrast: 0.9803855339996517
purpose: []
